const data = {
    products:[
        {
            _id:'1',
            name:'Dr. Martens',
            category:'Shoes',
            image:'/images/p1.jpg',
            price: 120,
            countInStock:10,
            brand:'Dr. Martens',
            rating: 4,
            numReviews: 10,
            description:'High quality shoe',
        },

        {
            _id:'2',
            name:'Balenciaga',
            category:'Shoes',
            image:'/images/p2.jpg',
            price: 120,
            countInStock:9,
            brand:'Balenciaga',
            rating: 5,
            numReviews: 10,
            description:'High quality shoe',
        },
        {
            _id:'3',
            name:'Macbook Pro',
            category:'electronics',
            image:'/images/p3.jpg',
            price: 1200,
            countInStock: 20,
            brand:'Apple',
            rating: 5,
            numReviews: 16,
            description:'High quality laptop',
        },
        {
            _id:'4',
            name:'Iphone 12 pro max',
            category:'phones',
            image:'/images/p4.jpg',
            price: 999,
            countInStock: 0,
            brand:'Apple',
            rating: 5,
            numReviews: 10,
            description:'High quality phone',
        },
        {
            _id:'5',
            name:'Jordans',
            category:'shoes',
            image:'/images/p5.jpg',
            price: 220,
            countInStock: 12,
            brand:'Jordans',
            rating: 4,
            numReviews: 10,
            description:'High quality Shoe',
        },
    ],
};
export default data;